name: Sync Label
description: Sync a label to labels.yaml

inputs:
  action:
    required: true
    description: The action performed on the label, can be created, edited, or deleted.
  name:
    required: true
    description: The name of the label being synced.
  color:
    required: true
    description: The color of the label being synced.
  description:
    required: false
    description: The description of the label being synced.

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Sync label
      shell: bash
      run: |
        chmod +x ./.github/scripts/sync-label.py
        ./.github/scripts/sync-label.py ${{ inputs.action }} ${{ inputs.name }} ${{ inputs.color }} ${{ inputs.description }}
    - name: Auto commit label sync
      uses: stefanzweifel/git-auto-commit-action@v4
      id: commit_id
      with:
        commit_message: 'chore: Update label'
        create_branch: false
        branch: trunk
