name: Sync Labels
on:
  label:
    types:
      - created
      - edited
      - deleted

jobs:
  sync:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/composite/sync-label
        with:
          action: ${{ github.event.action }}
          name: ${{ github.event.label.name }}
          color: ${{ github.event.label.color }}
          description: ${{ github.event.label.description }}

      - name: Fetch all repos in org
        uses: denis-tingaikin/get-organization-repositories@v1
        id: org_repos
        with:
          github-organization: 'atsign-foundation'

      - name: Sync labels to all repos
        uses: micnncim/action-label-syncer@v1
        with:
          manifest: ./.github/labels.yml
          repository: xavierchanth/cross-actions-receiver
          token: ${{ github.token }}
